coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%

ignore:
  - "__tests__/**"
  - "**/*.test.ts"
  - "**/*.test.tsx"
