/**
 * Service centralisé pour le mapping des artistes vers les genres
 * À remplacer par une vraie API de genres (Last.fm, MusicBrainz, etc.) dans le futur
 */

/**
 * Mapping simplifié des artistes vers les genres
 */
export const ARTIST_TO_GENRE_MAP: Record<string, string> = {
  "The Weeknd": "R&B",
  "Dua Lipa": "Pop",
  "Taylor Swift": "Pop",
  "Arctic Monkeys": "Indie Rock",
  "Kendrick Lamar": "Hip-Hop",
  "Daft Punk": "Electronic",
  "Bon Iver": "Indie Folk",
  "Beach House": "Dream Pop",
  "Sheta Spoon": "African music",
  "El Elyon": "African music",
  "La harpe de David": "Gospel",
  "Dorcas Kaja & Les Soeurs": "Gospel",
  "Tout est Jazz": "Gospel",
  "Olivier Kalabasi": "Gospel",
  "A la FYK": "Gospel",
  "Glory Mundeke": "Gospel",
  "Elie David Domingos": "Gospel",
  "SisiK": "Hip hop",
  "LORD LOMBO": "Gospel",
  "Naza & Niska": "Hip hop",
  "Maestro Bang": "Afrobeats",
  "Mital": "Gospel",
  "Nk Divine": "Gospel",
  "Josue S. Domingos": "Gospel",
  "Frenna, Boef & DJ Madam Julie": "Afrobeats",
  "Niska & Tiakola": "Hip hop",
  "Yvan Music and Qo": "Gospel",
  "Studio Mezzo": "Gospel",
  "Carlton Easton": "Gospel",
  "Yxng Le & Frenna": "Afrobeats",
  "Imengo Manassé, Ariol Mata, Manu Swing, Thierry Caps, Meres LF, Maceo Saxman, Marvin Kln, Doudou Drum & Emma plus": "Gospel",
  "Olivier Kalabasi & El Bethel": "Gospel",
  "Alka Mbumba": "Gospel",
  "Imengo Manassé, Manu Swing, Noah Drum, Abdias Synthe, Doudou Drum & Stumi Full": "Gospel",
  "Gato, Booba & Bramsito": "Hip hop",
  "Clark Donovan & Les Masqués": "African music",
  "CONGO WORLDWIDE": "African music",
  "TINI & Greeicy": "Latin",
  "Molaré": "African music",
  "Team Music": "Gospel",
  "Life Musica": "African music",
  "Mix Premier": "African music",
  "Rolls Des Nuances": "African music",
  "IDPizzle": "African music",
  "PhillBill": "Cameroon music",
  "Sharon Ndongala": "African music",
  "Ange Mbyal": "Gospel",
  "Beni Kibala": "Gospel",
  "RD Muzik": "Gospel",
  "Aggée Ntandu": "Gospel",
  "Le Motif & Junior Alaprod": "Hip hop",
  "GKGD & Family": "Gospel",
  "Bibinho De Gaucho": "African music",
  "Bruce J Lubaki": "Gospel",
  "La Massia": "Gospel",
  "Isaac G": "Hip hop",
  "4Keus & No Limit": "Hip hop",
  "Priscah Kane": "African music",
  "Grupo Frontera & Grupo Firme": "Latin",
  "Samy Lrzo & Gambino La MG": "Hip hop",
  "12 World Plus": "African music",
  "Happy D'efoulan": "Cameroon music",
  "DJ Sams": "African music",
  "ZDRID FAMILY": "Afrobeats",
  "Mercenaires": "African music",
  "Vegedream & Lafropop": "Afrobeats",
  "Pedro Capó & Farruko": "Latin",
  "KeBlack & Naza": "Hip hop",
  "Quartier Bbsprodmusic": "Gospel",
  "Alpha Music": "Gospel",
  "CDG": "Afrobeats",
  "Deplick Pomba": "African music",
  "Samy Lrzo & Waïv": "Afrobeats",
  "Kamal Beatmaker": "Afrobeats",
  "Imengo Manassé, Manu Swing, Nathan Pongo, Manu Kabs, JNR La main de fer, Abdias Synthe, Danny Mbonda, Paul Kabeya, Christian Litasi & Benjamin Boketshu": "Gospel",
  "N2C": "Afrobeats",
  "MPR (Music Populaire de la Revolution)": "African music",
  "DJ KEROZEN & Magic System": "African music",
  "Ndombolhino": "African music",
  "Niska & Hamza": "Hip hop",
  "Koffi Olomidé & Quartier Latin": "African music",
  "Mayorkun & Davido": "Afrobeats",
  "MARINO LELE Lumoselta": "African music",
  "Ks Bloom": "African music",
  "Jungeli, Imen Es & Alonzo": "Afrobeats",
  "Les Leaders": "African music",
  "Deejay Clyde": "Afrobeats",
  "Liim's": "Hip hop",
  "Koba LaD & Naps": "Hip hop",
  "Ntaba 2 London": "Afrobeats",
  "Ashley Baker": "Country",
  "S.Pri Noir & 4Keus": "Hip hop",
  "Santrinos Raphael & Debordo Leekunfa": "African music",
  "Imengo Manassé, Grace Siku, Joel Nkuluba, Prodige Sadi, Rabby Lema, Luc Bomboli, Gedeon Dagloir, JIMMY MBONDA, Christian Martinez, Mils Mayolo & Christian Litasi": "Gospel",
  "Ben Decca & Grace Decca": "Cameroon music",
  "Priscilia Twambi": "Gospel",
  "Desko Youknow": "Hip hop",
  "Britannie": "World",
  "Leto & Guy2Bezbar": "Hip hop",
  "Niska & Maes": "Hip hop",
  "L'evangéliste Prosper TSB": "Gospel",
  "Les Médecins De Medelin": "Cameroon music",
  "TeeZandos & Midas the Jagaban": "Hip hop",
  "Mike Kalambay": "Gospel",
  "Fiston Mbuyi": "Gospel",
  "Ladiako interplanétaire": "African music",
  "Boris Reine-adelaide": "African music",
  "Jiova Jiova": "Afrobeats",
  "Grupo Frontera & Junior H": "Latin",
  "Gazo & Tiakola": "Hip hop",
  "Timal": "Hip hop",
  "Grupo Frontera & Ke personajes": "Latin",
  "GIMS & DYSTINCT": "Hip hop",
  "Frenna & Lil Kleine": "Afrobeats",
  "Christian Bombole": "Gospel",
  "Imengo Manassé, Paul Kabeya, Arche De Noé & JIMMY MBONDA": "Gospel",
  "Dosseh & Tiakola": "Hip hop",
  "Ikaz Boi & Tiakola": "Hip hop",
  "SDM, Green Montana & Booba": "Hip hop",
  "Kerdy vuvu": "Gospel",
  "Edgar Joel & Anthony Colon": "Latin",
  "Mavins, Rema & Boy Spyce": "Afrobeats",
  "Les Citoyens du Royaume": "Gospel",
  "Kalash & Damso": "Hip hop",
  "wilsko": "Hip hop",
  "MCBOX": "Hip hop",
  "Tiakola & Merveille": "Hip hop",
  "Niska & Ninho": "Hip hop",
  "Flavour, Fally Ipupa & Diamond Platnumz": "African music",
  "Broederliefde & Frenna": "Afrobeats",
  "Cadie Nelva": "World",
  "Judikay": "Gospel",
  "Santrinos Raphael & Zeynab": "African music",
  "Kris Kross Amsterdam, Maan & Tabitha": "Afrobeats",
  "Cédric Béton": "African music",
  "Witty Minstrel": "Cameroon music",
  "Amima": "Hip hop",
  "Sisi K & Logobi GT": "Hip hop",
  "Sergeo Polo": "Cameroon music",
  "Imengo Manassé, Max Maxwell, Désiré Logo, Gedeon Dagloir, Junior Bakunda & Mode Ngeni": "Gospel",
  "LZ & Alibi Montana": "Afrobeats",
  "Israel Nakweti": "Gospel",
  "La Relance": "Afrobeats",
  "JB Mpiana & Wenge BCBG": "African music",
  "Le Groupe Rehoboth de Londres": "Gospel",
  "Jack Flaag": "Hip hop",
  "Imengo Manassé, Aggée Ntandu, Bruce Lubaki, Godé Lofumbo, Chancy Le Prince, Gedeon Dagloir, JIMMY MBONDA & Christian Litasi": "Gospel",
  "Mr Leo": "Cameroon music",
  "Dashikos": "Gospel",
  "Davido & Chris Brown": "Afrobeats",
  "De Mthuda, Da Muziqal Chef & Eemoh": "World",
  "Samy Lrzo & SenSey'": "Hip hop",
  "Divine Brenda": "Gospel",
  "Marino Lele": "Gospel",
  "Kelly Rowland featuring Nelly": "Hip hop",
  "Fireboy DML & Asake": "Afrobeats",
  "Niska & Mayo": "Hip hop",
  "Imengo Manassé, Joel Nkuluba, Marvin Kln, Kemy Siala, Ange Kayaya, Meschac Tshoumou, Christian Martinez, Pasteur Samuel Meya & Christian Litasi": "Gospel",
  "FloyyMenor & Cris MJ": "Latin",
  "Dj Kawest & Vayb": "World",
  "Doliziana Debordo": "African music",
  "Booba & USKY": "Hip hop",
  "Heezy Lee & Le Motif": "Hip hop",
  "Ninho & Serge Ibaka": "Hip hop",
  "Petio Clique": "Hip hop",
  "Farruko, Victor Cardenas & Dj Adoni": "Latin",
  "Les Marquis de Maison Mère": "African music",
  "Maes & Gazo": "Hip hop",
  "Kalash & Gazo": "Hip hop",
  "Grâce Valerie": "Gospel",
  "Rvfv & Rels B": "Latin",
  "RK Play": "Gospel",
  "Niska & Liim's": "Hip hop",
  "Sesman": "Latin",
  "Gazo, Kerchak, Leto & Favé": "Hip hop",
  "113, Magic System & Mohamed Lamine": "French",
  "disiz & Damso": "Hip hop",
  "Longué longué": "Cameroon music",
  "Shesko l'emeraude": "African music",
  "David Rodrinho": "African music",
  "Niska & Zed": "Hip hop",
  "Kaaris & GIMS": "Hip hop",
  "Kaaris & Imen Es": "Hip hop",
  "DJ J-Style": "World",
  "Patrick Fiori, Garou & Daniel Lavoie": "French",
  "Highlyy & Tion Wayne": "Hip hop",
  "Fresh & Naza": "Hip hop",
  "NSG & MIST": "Hip hop",
  "ARMÉE CÉLESTE": "Gospel",
  "Dinh VZ": "World",
  "Dj Yoros": "African music",
  "Kizz Daniel & Davido": "Afrobeats",
  "Tour 2 Garde": "African music",
  "Les Médecins de Medeline": "Cameroon music",
  "Rondodasosa & Nko": "Cameroon music",
  "No Limit, Gazo & Damso": "Hip hop",
  "S.Pri Noir & Alonzo": "Hip hop",
  "Scory Kovitch, Noah Lunsi & T Matt": "Afrobeats",
  "ZEG P": "Electronic",
  "Kerchak & Alonzo": "Hip hop",
  "Jogga, wilsko & Marjinal": "Afrobeats",
  "Manuel Turizo & Grupo Frontera": "Latin",
  "Aya Nakamura & Naza": "Hip hop",
  "KeBlack & Joé Dwèt Filé": "Hip hop",
  "Adorons L'éternel": "Gospel",
  "Aze2dine": "Hip hop",
  "Dany B": "Hip hop",
  "Fuerza Regida & Marshmello": "Latin",
  "Denzo & Koba LaD": "Hip hop",
  "DJ Erise & Naza": "Hip hop",
  "Bryan Mg & Frenna": "Afrobeats",
  "Naza & Dj Leska": "Hip hop",
  "Davido & Popcaan": "Afrobeats",
  "Soolking & Gazo": "Hip hop",
  "Meryl & Le Motif": "Hip hop",
  "Blacky & Christbnd": "Gospel",
  "Doxmv": "Hip hop",
  "Le Maki": "Hip hop",
  "The Weeknd & Suzanna Son": "Pop",
  "Azize Diabate": "African music",
  "Costaud": "Hip hop",
  "Carlton Djouffel": "Afrobeats",
  "KRN & Booba": "Hip hop",
  "Samy Lrzo & EvanV": "Hip hop",
  "Meres_LF": "African music",
  "FAMILLE CORPS DU CHRIST": "Gospel",
  "Q.E Favelas": "Hip hop",
  "Noah Lunsi": "Hip hop",
  "Wenge BCBG & JB Mpiana": "African music",
  "JSX & Booba": "Hip hop",
  "4TS": "Hip hop",
  "Doks": "Afrobeats",
  "DJ Marechal": "African music",
  "Cash Cobain, Ice Spice & Bay Swag": "Hip hop",
  "Cuppy & Tekno": "Afrobeats",
  "GIMS, Dadju & Alonzo": "Hip hop",
  "Roga Roga, Dany Synthé & Yorssy": "Hip hop",
  "Nobuyuki Tsujii & EXILE ATSUSHI": "World",
  "Mayorkun & Joeboy": "Afrobeats",
  "Cash Crime": "Hip hop",
  "USKY & Booba": "Hip hop",
  "Jox Diangituka": "Gospel",
  "Tayc, Shreya Ghoshal & Rajat Nagpal": "Afrobeats",
  "Sanks Amg": "Afrobeats",
  "Marvin & Phyllisia Ross": "World",
  "Blanco & NSG": "Hip hop",
  "Kris Kross Amsterdam, Kraantje Pappie & Pommelien Thijs": "Afrobeats",
  "Les Masqués": "African music",
  "Scotty BK": "African music",
  "Tiakola & Ronisia": "Hip hop",
  "Kenzaro": "African music",
  "Teevii": "Hip hop",
  "Yvan Music and Qo & paty matemo": "Gospel",
  "Seysey & Genezio": "Hip hop",
  "Vizou": "Afrobeats",
  "Bouzzy": "Hip hop",
  "Tiakola, Ryflo & Oskoow": "Hip hop",
  "SAINT CLARENCE": "Hip hop",
  "Dj Kawest, Gaëlle & Chily": "Afrobeats",
  "Eye's Berg": "Hip hop",
  "Liim's & Gazo": "Hip hop",
  "KABONGO-DJ & Vegedream": "Hip hop",
  "Dj Ralph Bb & DJ Inno": "World",
  "Darkoo & One Acen": "Hip hop",
  "Dadju & Sofiane": "Hip hop",
  "Jonathan Gambela & Yolaine BM": "Gospel",
  "DJ Vielo & DJ Anilson": "Hip hop",
  "Popaul Amisi": "African music",
  "Ilover": "Gospel",
  "Symphonic Rock Project": "Rock",
  "Los Grumos": "Latin",
  "Ndedi Dibango": "Afrobeats",
  "20Th Square": "Hip hop",
  "Alan Walker & Ava Max": "Electronic",
  "Damien Sargue, Cyril Niccolaï & John Eyzen": "French",
  "680 Celsus": "Hip hop",
  "Sidiki Diabaté, *Iba One* & Niska": "Hip hop",
  "BRVMSOO": "Hip hop",
  "Ali B & Numidia": "Afrobeats",
  "César Bâton de Moïse": "African music",
  "Shakalewa": "African music",
  "Fally Ipupa featuring Krys": "African music",
  "Guy2Bezbar & Leto": "Hip hop",
  "Bryan Mg & DYSTINCT": "Afrobeats",
  "Locko & Mr Leo": "Cameroon music",
  "Maejor & Greeicy": "Afrobeats",
  "Dr. Yaro": "Hip hop",
  "DJ Peet": "Hip hop",
  "SARAFINA THE GREAT": "Afrobeats",
  "Joé Dwèt Filé & Lil Jay Bingerack": "Afrobeats",
  "Lamatrix": "Hip hop",
  "Venom Cascadeur": "Hip hop",
  "Daïcha Dikondja, Jessica Ndongola, Deborah Loma & Gracia Odile": "Gospel",
  "Lil Wayne & Jennifer Lopez": "Pop",
  "José Tshiabuiye": "Gospel",
  "Mikl": "World",
  "Nesly & Vegedream": "Hip hop",
  "Lous and The Yakuza, Sfera Ebbasta & Shablo": "Hip hop",
  "Jonathan Bitolo & Clarkson": "Gospel",
  "VMA9K": "Hip hop",
  "Dj Kawest & Innoss'B": "African music",
  "Tiago PZK & Ke personajes": "Latin",
  "Troniq Music & Oxlade": "Afrobeats",
  "Frad & bloom.": "Pop",
  "Fresto Music": "Latin",
  "Seben CONGO": "African music",
  "Tiakola, Genezio & Prototype": "Hip hop",
  "Key Largo & 4Keus": "Hip hop",
  "09zer": "Hip hop",
  "DJ Maréchal": "African music",
  "DJ Neptune, Joeboy & Mr Eazi": "Afrobeats",
  "Papi Del Sol": "Latin",
  "Meygi Correia": "African music",
  "Tiakola, Rsko & Hamza": "Hip hop",
  "DJ Keishawn & Curtis Kane": "World",
  "Genezio & Dadju": "Hip hop",
  "Tai, Massiv3, Dee End, O.Z & Rosalvo": "World",
  "HASSBOSS": "Afrobeats",
  "4.4.2, Tayc & Soolking": "Hip hop",
  "Carlton Djouffel & King Draga": "African music",
  "Gino J, Hulk Van JMF & Tayron Kwidan's": "Afrobeats",
  "Prototype, Kodes & Liim's": "Hip hop",
  "Aya Nakamura & Joé Dwèt Filé": "Hip hop",
  "Mekaddishkem": "Gospel",
  "Efra Kinumbe": "Gospel",
  "Landy & MC Menor JP": "Hip hop",
  "Ninho & Omah Lay": "Hip hop",
  "Isaac BUKASA": "Gospel",
  "Dj Kawest & Kim": "World",
  "5 car ecco": "African music",
  "Ninho & Niro": "Hip hop",
  "Senior Sensy": "Afrobeats",
  "Central Cee & Lil Durk": "Hip hop",
  "Aveiro Djess": "Cameroon music",
  "Papa Keke": "African music",
  "Vanister": "Cameroon music",
  "SenSey', Vegedream & Youka": "Afrobeats",
  "Crew Celeste & Diim's La Betise": "Gospel",
  "Kedjévara": "African music",
  "Ghost Killer Track": "Hip hop",
  "Vegedream & Dj Leska": "Hip hop",
  "Banx & Ranx & Kojo Funds": "Afrobeats",
  "Tayron Kwidan's & Gael Stone": "Hip hop",
  "Matota Beat": "Gospel",
  "ZOKUSH": "Hip hop",
  "6ix9ine, ANGEL DIOR & Lenier": "Hip hop",
  "Maes & Niska": "Hip hop",
  "Pheno Ambro": "African music",
  "Bryans": "World",
  "Jogga, wilsko & Iselena": "Hip hop",
  "Mokobé & Fally Ipupa": "African music",
  "Major Lazer, MØ & DJ Snake": "Hip hop",
  "Anges D'Afrik": "African music",
  "Manybeat & JJ Romero": "Latin",
  "Magic System, Yemi Alade & Mohamed Ramadan": "African music",
  "Tiakola, JEY BROWNIE & Sonny Rave": "Hip hop",
  "Yandel, Feid & Daddy Yankee": "Latin",
  "Moona": "Latin",
  "Calle 24, Chino Pacas & Fuerza Regida": "Latin",
  "Nickson & Bryans": "World",
  "Bramsito & Tayron Kwidan's": "Hip hop",
  "Locko & Bramsito": "African music",
  "Oskoow": "Hip hop",
  "Kedjevara & Antoinette alany": "African music",
  "F1rstman, Boef & DJ Youss-F": "Hip hop",
  "DJ Kero": "African music",
  "Kaaris, Kalash Criminel & Freeze Corleone": "Hip hop",
  "W Sound, Beéle & Ovy On the Drums": "Latin",
  "Imen Es & Franglish": "Hip hop",
  "tkss": "Hip hop",
  "SAF & Samy Lrzo": "Hip hop",
  "Jimah": "Afrobeats",
  "Ziimondo": "Hip hop",
  "Super Tshim": "Gospel",
  "D'Tunes": "Afrobeats",
  "Blaxco, KEN'ZII BWA, RADIKAL BWA & TI MWAKA": "World",
  "Breetany": "World",
  "Damso & Blynk": "Hip hop",
  "Waïv": "Hip hop",
  "Lartiste, Busy Signal & Da XL Team": "Hip hop",
  "KAROL G & Peso Pluma": "Latin",
  "Samy Lrzo & Kiko": "African music",
  "Maes, Tiakola & Zed": "Hip hop",
  "Harley & OBOY": "Hip hop",
  "Grupo Frontera & Maluma": "Latin",
  "LIMO & SenSey'": "Hip hop",
  "Dave & Wizkid": "Afrobeats",
  "SFB, Frenna, Priceless, Jandro, Murda & KM": "Afrobeats",
  "Daarkskiinn": "Hip hop",
  "Ariol Mata Mazembe, Yvan Music and Qo & Ridge Mondany": "Gospel",
  "Vanister Enama": "Cameroon music",
  "Edem Drackey": "African music",
  "Dj Kawest & Ntaba 2 London": "Afrobeats",
  "Liim's & Franglish": "Hip hop",
  "AJ x Deno": "Hip hop",
  "Katshiame": "Hip hop",
  "Piso 21 & Micro Tdh": "Latin",
  "Carbonne": "French",
  "Dj Kawest & DK2fois": "Afrobeats",
  "Landy & Franglish": "Hip hop",
  "Team Influence 2.0": "Cameroon music",
  "Kalash Criminel & Kaaris": "Hip hop",
  "Serge Ibaka, Bill Clinton, Tidiane Mario & Afara Tsena": "African music",
  "Bercy Mwana": "African music",
  "Jonathan KUTI": "Gospel",
  "Serge Ibaka, Papi Del Sol & Lil Jay Bingerack": "Latin",
  "DJ Erise & Joé Dwèt Filé": "World",
  "Darkoo & Rema": "Hip hop",
  "Shizzi, Teni & Mayorkun": "Afrobeats",
  "Yetii Mpini": "African music",
  "Gaz Mawete & Ya Levis": "African music",
  "Dj Kawest & Emma'a": "Afrobeats",
  "Vincè la petite culotte": "French",
  "Grupo Frontera & Christian Nodal": "Latin",
  "Marline Millebaguettes": "Gospel",
  "Kim & Guy2Bezbar": "World",
  "IDP": "Afrobeats",
  "La Kadrilla": "Hip hop",
  "Riton & Nightcrawlers": "Electronic",
  "Franglish & Dinos": "Hip hop",
  "DJ Erise & KeBlack": "Hip hop",
  "Stonebwoy & Davido": "Afrobeats",
  "Mr P, Teni, Simi & Tamar Braxton": "Afrobeats",
  "RAF Camora, AriBeatz & Sofiane": "Hip hop",
  "DJ Erise & Franglish": "Hip hop",
  "Kaaris & TRIANGLE DES BERMUDES": "Hip hop",
  "Big One, FMK & Ke personajes": "Latin",
  "DJ Faya & Fally Ipupa": "African music",
  "Naza, CNN ALLIGA & Tuta Selo": "African music",
  "Jungeli, Vegedream & Alonzo": "Hip hop",
  "Bonzoo": "Hip hop",
  "Sam Manguana": "Cameroon music",
  "No Limit & 4Keus": "Hip hop",
  "La Merva": "Gospel",
  "Luck Ra, La K'onga & Ke personajes": "Latin",
  "5 car": "African music",
  "Fally Ipupa & Mokobé": "African music",
  "Bekar & SDM": "Hip hop",
  "Collectif Batshu": "Gospel",
  "Dance Fruits Music & Steve Void": "Electronic",
  "Deejay Telio & Deedz B": "Afrobeats",
  "Rockazzmusic": "Gospel",
  "Flavour & Umu obiligbo": "Afrobeats",
  "Jok'air, Vegedream & Marjinal": "Hip hop",
  "Aya Nakamura & SDM": "Hip hop",
  "Collectif Crystal Music": "Gospel",
  "N'do-Man": "Cameroon music",
  "Thomas Lokofe": "African music",
  "Juicy P & Kpoint": "Hip hop",
  "WengeMan": "African music",
  "mgk & Camila Cabello": "Latin",
  "Bombastiik": "Afrobeats",
  "B ONE SHAKAZULU": "African music",
  "Ronisia & Joé Dwèt Filé": "Hip hop",
  "DJ Quick, RK & DA Uzi": "Hip hop",
  "Kevv. & Qshans": "World",
  "Ashh": "Indie",
  "JAŸ-Z & Alicia Keys": "Pop",
  "Valentino Merlo & The La Planta": "Latin",
  "Dinos & Hamza": "Hip hop",
  "Ke personajes & Onda Sabanera": "Latin",
  "Patomant & Kxyyz": "Afrobeats",
  "NSG & PsychoYP": "Hip hop",
  "Ntaba 2 London, Guccima & Rolls Des Nuances": "Afrobeats",
  "Leto & Niska": "Hip hop",
  "Les Héritiers Céleste": "Gospel",
  "LeoStayTrill & Clean Bandit": "Pop",
  "Kilimandjaro": "Hip hop",
  "Shammah": "Gospel",
  "KM & Yxng Le": "Afrobeats",
  "Angelcy & Jungeli": "Hip hop",
  "Kavinsky, Angèle & Phoenix": "Electronic",
  "Kabuya": "African music",
  "Shades & Bilouki": "Hip hop",
  "Dinos & Laylow": "Hip hop",
  "7iaa": "Afrobeats",
  "Toofan & Sidiki Diabaté": "African music",
  "EBOLOKO": "African music",
  "Arafat & Debordo": "African music",
  "Youka, Cyril Kamer & Big Papa313": "Latin",
  "Grupo Frontera & Carín León": "Latin",
  "Lixx & Ref Rondo": "Hip hop",
  "La Jet Set": "Hip hop",
  "Hulk Van JMF & Chily": "Afrobeats",
  "Christbnd": "Gospel",
  "Samy Lrzo & Tayron Kwidan's": "Afrobeats",
  "Ibara": "Afrobeats",
  "&ME & Black Coffee": "Afrobeats",
  "Nk Divine & Athom's Mbuma": "Gospel",
  "DJ Snake & Hamza": "Electronic",
  "DJ Matrix & Matt Joe": "Electronic",
  "Dj Roberto Da'Silva": "Latin",
  "DJ KEROZEN & Didier Awadi": "African music",
  "Bozi Boziana & l'Anti Choc": "African music",
  "Yo Joshy": "Hip hop",
  "Molaré, Too Fan & Wizboyy": "African music",
  "Petit Axel": "African music",
  "Kratos le Dieu de la guerre": "Cameroon music",
  "Wejdene & Heuss L'enfoiré": "Hip hop",
  "GloRilla, Kirk Franklin, Maverick City Music, Kierra Sheard & Chandler Moore": "Gospel",
  "Warren Saada & Dadju": "Hip hop",
  "Elton John & Thom Bell": "Pop",
  "Bilouki & Oskoow": "Hip hop",
  "Yung Felix & Poke": "Hip hop",
  "Genezio & GIMS": "Hip hop",
  "Gonzy, SAIKO & Arcángel": "Latin",
  "DJ ABDO": "Latin",
  "GIMS & Maluma": "French",
  "Yapi & Arcones": "Latin",
  "SenSey' & RK": "Hip hop",
  "DJ TV3": "African music",
  "Ramzy Jordan": "Pop",
  "Niphkeys & Not3s": "World",
  "Fireboy DML & D Smoke": "Afrobeats",
  "GIMS, SativaMusic & Morad": "French",
  "HENRY LONDOLA": "Gospel",
  "Chynaunique ASMR": "World",
  "Fonseca & Rawayana": "World",
  "Wejdene & Nej": "French",
  "S.Pri Noir & Dadju": "Hip hop",
  "Tom Dice & Elisa Tovati": "French",
  "Abraham Kiyaba": "Gospel",
  "Isaac M.": "Gospel",
  "Layanah": "World",
  "Kizz Daniel & Tekno": "Afrobeats",
  "Beri Boys Club": "Cameroon music",
  "Master KG & Nomcebo Zikode": "Afrobeats",
  "Blessd & Ovy On the Drums": "Afrobeats",
  "Prince Aimé, Maahlox Le Vibeur & Magasco": "Cameroon music",
  "Virtuoz & Gael Stone": "Afrobeats",
  "Rvfv, Youka & Wesh Music": "Latin",
  "Béatrice Gnoupalé": "Gospel",
  "DK2fois & Nayth": "Afrobeats",
  "Dadju & Ronisia": "Hip hop",
  "Adam Port, Stryv & Malachiii": "World",
  "Feid & Rema": "Latin",
  "5 car ecco & Ntaba 2 London": "African music",
  "Rey De Rocha & Prince Nico Mbarga": "Latin",
  "Grupo Frontera & NICKI NICOLE": "Latin",
  "Tshoums": "Folk",
  "איתי לוי & עידו שוהם": "World",
  "Collectif JCLM, Kabuya Fumu, Tuta Selo & Ya Deidei": "Gospel",
  "Metro Boomin, The Weeknd & Diddy": "Hip hop",
  "Jack Harlow & Lil Nas X": "Hip hop",
  "Werenoi & GIMS": "Hip hop",
  "Wejdene & Alonzo": "Hip hop",
  "Jungeli & Lenie": "French",
  "Vegedream & Warren Saada": "Hip hop",
  "Crew Celeste": "Gospel",
  "ELENA ROSE, Danny Ocean & Jerry Di": "Latin",
  "Niaks & Naza": "Hip hop",
  "Samy Lrzo & SeNSeY": "Hip hop",
  "Tiakola, SDM & Liim's": "Hip hop",
  "Bazzarba": "Hip hop",
  "Elton John, Young Thug & Nicki Minaj": "Pop",
  "Stormy & Tagne": "Hip hop",
  "100 % Compil": "Cameroon music",
  "Gaëlle & Fresh": "Hip hop",
  "IN.94, Bilouki & Yorssy": "Hip hop",
  "Martin Garrix, Dimitri Vegas & Like Mike & Shouse": "Electronic",
  "Remuta": "Hip hop",
  "Le D & Bolémvn": "Hip hop",
  "Novox & Karaokey": "Hip hop",
  "DCartier & Gino J": "Afrobeats",
  "Mike Alabi": "Gospel",
  "GIMS & KeBlack": "Hip hop",
  "Flavour & Semah": "African music",
  "Singuila & Youssoupha": "World",
  "MODELKI & Vłodarski": "Pop",
  "Lexsil & Tayron Kwidan's": "Afrobeats",
  "SenSey' & Bramsito": "Hip hop",
  "GIMS & Damso": "Hip hop",
  "100Limites": "Hip hop",
  "Zaïko Langa Langa & Jossart Nyoka Longo": "African music",
  "Sech, Ozuna & Anuel AA": "Latin",
  "Lin's": "Hip hop",
  "Dinos & Bamby": "Hip hop",
  "Jul, SCH, Naps, Kofs, Elams, Solda, Houari & Soso Maness": "Hip hop",
  "Paradis Français": "French",
  "Young Miko & Feid": "Latin",
  "Dosseh & Zequin": "Hip hop",
  "Gradur, SDM & Rsko": "Hip hop",
  "Dy La Mano": "Hip hop",
  "Vicoka": "Hip hop",
  "Ama Pierro": "Gospel",
  "BRAN, AFRONOM & Mannymore": "Afrobeats",
  "THB SOLDIERS": "Cameroon music",
  "SAIKO, Dei V & JC Reyes": "Latin",
  "Faceless & Serøtonin": "Afrobeats",
  "Wizolingo": "Afrobeats",
  "NSG & LYVIA": "Hip hop",
  "Le Rain-T": "Hip hop",
  "Benge Kiese": "Gospel",
  "Jessie Reyez & Lil Yachty": "Pop",
  "Fally Ipupa, KLN, Merveille & Dany Synthé": "African music",
  "Dj LK da Escócia, Tchakabum & MC Ryan SP": "Latin",
  "3B": "Afrobeats",
  "Magic System & Soolking": "Afrobeats",
  "Dexta Daps, Tory Lanez & Louie Culture": "Hip hop",
  "Megaski": "Hip hop",
  "Gabriel Dominguez": "Latin",
  "Zola & Koba LaD": "Hip hop",
  "Petit Bozard": "Cameroon music",
  "Fally Ipupa featuring Benji": "African music",
  "Gaëlle & Jungeli": "Hip hop",
  "Alzate": "Latin",
  "Nathan Updc & Jordy": "African music",
  "Bramsito & Lossa": "Hip hop",
  "Hulk Van JMF & TROCSTAR": "Afrobeats",
  "Wejdene & Kany": "Pop",
  "Attachingboy": "Hip hop",
  "Louzio": "Hip hop",
  "kulturr & Merveille": "Hip hop",
  "Sisi K & BB Model": "Hip hop",
  "King Promise & Gabzy": "Afrobeats",
  "Soso Maness & PLK": "Hip hop",
  "JunLIB": "Hip hop",
  "Smur Lee & ODUMODUBLVCK": "Latin",
  // Ajoutez plus de mappings selon vos besoins
};

/**
 * Fonction helper pour obtenir le genre d'un artiste
 * Retourne "Unknown" si l'artiste n'est pas dans le mapping
 */
export function getGenreForArtist(artistName: string): string {
  return ARTIST_TO_GENRE_MAP[artistName] || "Unknown";
}



